global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'fedcarrier'
    static_configs:
      - targets:
        - 'host.docker.internal:5010'  # FedCarrier.Order
        - 'host.docker.internal:5011'  # FedCarrier.Shipment
        - 'host.docker.internal:5012'  # FedCarrier.Billing
        - 'host.docker.internal:5013'  # FedCarrier.Notification
        - 'host.docker.internal:5014'  # FedCarrier.Saga
        - 'host.docker.internal:5015'  # FedCarrier.Tracking
        - 'host.docker.internal:5016'  # FedCarrier.Fleet
        - 'host.docker.internal:5017'  # FedCarrier.Customer
        - 'host.docker.internal:5018'  # FedCarrier.Driver
        - 'host.docker.internal:5019'  # FedCarrier.Reporting
        - 'host.docker.internal:5020'  # FedCarrier.Warehouse
        - 'host.docker.internal:5021'  # FedCarrier.Routing
        - 'host.docker.internal:5022'  # FedCarrier.Identity